#!/bin/bash

#Just for convenience during development - with externalized config properties
gradle clean build; java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -jar web/build/libs/orville-2.0.0-RC2.war --debug --spring.config.location=file:/etc/openregistry/config/openregistry.properties
