#!/bin/bash

#Just for convenience during development - with externalized config properties
gradle clean build; java -jar web/build/libs/openregistry-web-2.0.0-M2.jar --debug --spring.config.location=file:/etc/openregistry/config/openregistry.properties
